apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev

resources:
  - ../../base

configMapGenerator:
  - behavior: merge
    files:
      - application-dev.yaml
    name: catalog-service-config

images:
  - name: catalog-service
    newName: catalog-service
    newTag: latest

patches:
  - path: patch-env-dev.yaml
    target:
      kind: Deployment
      name: catalog-service
