spring:
  application:
    name: catalog-service

  datasource:
    username: catalog_service
    password: P@ssw0rd
    url: jdbc:postgresql://localhost:5432/catalog_service
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 5
  sql:
    init:
      mode: always
server:
  port: 9091
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5
