spring:
  application:
    name: dispatcher-service

  cloud:
    function:
      definition: pack|label # this property lets you declare which functions you want Spring Cloud Function to manage and integrate, resulting in a specific data flow.
    stream:
      bindings:
        packlabel-in-0:
          destination: order-accepted
          group: ${spring.application.name}
          content-type: application/json
        packlabel-out-0:
          destination: order-dispatched

  rabbitmq:
    host: ${RABBIT_MQ_HOST:localhost}
    port: ${RABBIT_MQ_PORT:5672}
    username: ${RABBIT_MQ_USERNAME:user}
    password: ${RABBIT_MQ_PASSWORD:password}
    connection-timeout: 5s

server:
  port: 9003

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, metrics, env
  endpoint:
    health:
      probes:
        enabled: true
      show-components: always
      show-details: always
  tracing:
    sampling:
      probability: 1.0
    export:
      enabled: true
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: http://localhost:4317
    resource-attributes:
        service.name: ${spring.application.name}
  otlp:
    metrics:
      export:
        enabled: false

  metrics:
    tags:
      application: ${spring.application.name}
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true
    build:
      enabled: true