### get all books
GET http://localhost:9091/books


### create new book
POST http://localhost:9091/books
Content-Type: application/json

{
  "isbn": "0098765432",
  "title": "Spring Boot 3",
  "author": "Mohammed Yehia",
  "price": 55,
  "version": 0
}


### find book by isbn
GET http://localhost:9091/books/0098765432
Content-Type: application/json


### get orders
GET http://localhost:9092/orders
Content-Type: application/json


### create new order
POST http://localhost:9092/orders
Content-Type: application/json

{
    "isbn": "0098765432",
    "quantity": 2
}



### get all books through API Gateway
GET http://localhost:9000/books

### get book by isbn through API Gateway
GET http://localhost:9000/books/0098765777

### create new book through API Gateway
POST http://localhost:9000/books
Content-Type: application/json

{
  "isbn": "0098765777",
  "title": "Cloud Native Java",
  "author": "Thomas",
  "price": 121,
  "version": 0
}

### get orders through API Gateway
GET http://localhost:9000/orders
Content-Type: application/json

### create new order through API Gateway
POST http://localhost:9000/orders
Content-Type: application/json

{
  "isbn": "0098765777",
  "quantity": 3
}