services:
  catalog-service:
    depends_on:
      - postgres-db
    container_name: catalog-service
    image: catalog-service
    ports:
      - '9091:9091'
    environment:
      BPL_JVM_THREAD_COUNT: 50
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/catalog_service

  postgres-db:
    container_name: postgres-ctr
    image: postgres:18.1
    restart: unless-stopped
    ports:
      - '5432:5432'
    volumes:
      - ./docker/volumes/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: catalog_service
      POSTGRES_PASSWORD: P@ssw0rd
      POSTGRES_DB: catalog_service

  order-service:
    depends_on:
      - mongo-db
    container_name: order-service
    image: order-service
    ports:
      - '9092:9092'
    environment:
      BPL_JVM_THREAD_COUNT: 50
      SPRING_MONGODB_URI: mongodb://mongo-db:27017/order_service
      CATALOG-SERVICE_URL: http://catalog-service:9091/books

  mongo-db:
    container_name: mongo-ctr
    image: mongo:4.4.29-focal
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - ./docker/volumes/mongo:/data/db

  api-gateway:
    depends_on:
      - redis
    container_name: api-gateway
    image: api-gateway
    ports:
      - '9000:9000'
    environment:
      CATALOG_SERVICE_URL: http://catalog-service:9091
      ORDER_SERVICE_URL: http://order-service:9092
      SPRING_DATA_REDIS_HOST: redis
      BPL_JVM_THREAD_COUNT: 50

  redis:
    container_name: redis-ctr
    image: redis:latest
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - ./docker/volumes/redis:/data

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.12-management
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - '5672:5672'
      - '15672:15672'
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3

#  product-service:
#    container_name: product-service
#    build:
#      context: ../product-service/.
#    environment:
#      RABBIT_MQ_HOST: ${RABBIT_MQ_HOST}
#      RABBIT_MQ_PORT: ${RABBIT_MQ_PORT}
#      RABBIT_MQ_USERNAME: ${RABBIT_MQ_USERNAME}
#      RABBIT_MQ_PASSWORD: ${RABBIT_MQ_PASSWORD}
