services:
  catalog-service:
    depends_on:
      - postgres-db
    container_name: catalog-service
    image: catalog-service
    ports:
      - '9091:9091'
    environment:
      BPL_JVM_THREAD_COUNT: 50
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/catalog_service

  postgres-db:
    container_name: postgres-ctr
    image: postgres:18.1
    restart: unless-stopped
    ports:
      - '5432:5432'
    volumes:
      - ./docker/volumes/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: catalog_service
      POSTGRES_PASSWORD: P@ssw0rd
      POSTGRES_DB: catalog_service