spring:
  application:
    name: api-gateway
  session:
    data:
      redis:
        namespace: spring:session
    timeout: 10m
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: catalog-service
              uri: ${CATALOG_SERVICE_URL:http://localhost:9091}/books
              predicates:
                - Path=/books/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: catalogCircuitBreaker
                    fallbackUri: forward:/catalog-fallback
            - id: order-service
              uri: ${ORDER_SERVICE_URL:http://localhost:9092}/orders
              predicates:
                - Path=/orders/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: orderCircuitBreaker
                    fallbackUri: forward:/order-fallback
            - id: spa-route
              uri: ${SPA_URL:http://localhost:9004}
              predicates:
                - Path=/,/*.css,/*.js,/favicon.ico
          httpclient:
            connect-timeout: 2000
            response-timeout: 5s
            pool:
              type: elastic
              max-idle-time: 15s
              max-life-time: 60s
          default-filters:
            - name: Retry
              args:
                retries: 3
                methods: GET
                series: SERVER_ERROR
                exceptions:
                  - java.io.IOException
                  - java.util.concurrent.TimeoutException
                backoff:
                  first-backoff: 50ms
                  max-backoff: 500ms
                  factor: 2
                  basedOnPreviousValue: false
            - name: SaveSession # instruct Spring Cloud Gateway to always save the web session before forwarding requests downstream.
            - name: TokenRelay # propagate the OAuth2 access token from the incoming request to downstream services.
            - name: RequestRateLimiter
              args:
                redis-rate-limiter:
                  replenishRate: 10 # number of tokens to add in the bucket each second
                  burstCapacity: 20 # maximum number of tokens in the bucket
                  requestedTokens: 1 # number of tokens required for each request
          redis-rate-limiter:
            include-headers: true
  data:
    redis:
      host: localhost
      port: 6379
      connect-timeout: 2s
      timeout: 1s

  security:
    oauth2:
      client:
        registration:
            keycloak:
                client-id: api-gateway
                client-secret: ${KEYCLOAK_CLIENT_SECRET:ITW6FxSOoabDc5ZCxbOPAfOKaeZm8UG1}
                authorization-grant-type: authorization_code
                scope:
                  - openid
                  - profile
                  - roles
        provider:
            keycloak:
                issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8180/realms/workshop}


server:
  port: 9001
  netty:
    connection-timeout: 2s
    idle-timeout: 15s

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 15s
        permittedNumberOfCallsInHalfOpenState: 3
    instances:
      catalogCircuitBreaker:
        baseConfig: default
      orderCircuitBreaker:
        baseConfig: default
  timelimiter:
    configs:
      default:
        timeout-duration:
          seconds: 5

logging:
  level:
    root: info
    org.springframework.cloud.gateway: trace
    org.springframework.security: trace
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: info
    io.github.resilience4j: DEBUG
    circuitbreaker: info
  group:
    circuitbreaker: io.github.resilience4j, org.springframework.cloud.circuitbreaker

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, metrics, env, gateway
  endpoint:
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true
      group:
        readiness:
          include: readinessState, redis
  tracing:
    sampling:
      probability: 1.0
    export:
      enabled: true

  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: http://localhost:4317
    resource-attributes:
        service.name: ${spring.application.name}

  otlp:
    metrics:
      export:
        enabled: false

  metrics:
    tags:
        application: ${spring.application.name}
        node: ${KUBERNETES_Node:${random.long}}
        namespace: ${KUBERNETES_NAMESPACE:default}
        instance.id: ${KUBERNETES_POD_NAME:${random.long}}


  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true
    build:
      enabled: true