apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: dev

configMapGenerator:
  - name: keycloak-config
    files:
      - realm-config.json

patches:
  - path: env-patch.yaml
    target:
      kind: Deployment
      name: workshop-keycloak