apiVersion: 1

deleteDatasources:
  - name: Prometheus
  - name: Tempo
  - name: Loki

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus-cn
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    basicAuth: false
    isDefault: false
    version: 1
    editable: true
    jsonData:
      exemplarTraceIdDestinations:
        - datasourceUid: tempo-cn
          name: traceID

  - name: Tempo
    type: tempo
    uid: tempo-cn
    access: proxy
    orgId: 1
    url: http://tempo:3200
    basicAuth: false
    isDefault: false
    version: 1
    editable: true
    jsonData:
      httpMethod: GET
      tracesToLogs:
        datasourceUid: 'loki-cn'
        tags: [ 'instance', 'pod', 'namespace', 'hostname' ]
        mappedTags: [ { key: 'service.name', value: 'container_name' }  ]
        mapTagNamesEnabled: true
        spanStartTimeShift: '-10m'
        spanEndTimeShift: '10m'
        filterByTraceID: true
        filterBySpanID: false
        lokiSearch: true
      lokiSearch:
        datasourceUid: 'loki-cn'
      serviceMap:
        datasourceUid: 'prometheus-cn'
      search:
        hide: false
      nodeGraph:
        enabled: true

  - name: Loki
    type: loki
    uid: loki-cn
    access: proxy
    orgId: 1
    url: http://loki:3100
    basicAuth: false
    isDefault: true
    version: 1
    editable: true
    jsonData:
      derivedFields:
        - datasourceUid: tempo-cn
          matcherRegex: \[.+,(.+?),
          name: TraceID
          url: $${__value.raw}