spring:
  application:
    name: order-service

  mongodb:
    uri: mongodb://localhost:27017/order_service
    username: order_service
    password: P@ssw0rd

server:
  port: 9092
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5
