spring:
  application:
    name: order-service

  mongodb:
    uri: mongodb://localhost:27017/order_service
    username: order_service
    password: P@ssw0rd

  rabbitmq:
    host: ${RABBIT_MQ_HOST:localhost}
    port: ${RABBIT_MQ_PORT:5672}
    username: ${RABBIT_MQ_USERNAME:user}
    password: ${RABBIT_MQ_PASSWORD:password}
    connection-timeout: 5s

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8180/realms/workshop}

  cloud:
    function:
      definition: dispatchOrder
    stream:
      bindings:
        dispatchOrder-in-0:
          destination: order-dispatched
          group: ${spring.application.name}
          content-type: application/json
        acceptOrder-out-0:
          destination: order-accepted
          content-type: application/json
      rabbit:
        bindings:
            dispatchOrder-in-0:
                producer:
                  transacted: true

server:
  port: 9092
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5

catalog-service:
  url: http://localhost:9091/books
  connection-timeout: 2
  read-timeout: 3