server:
  http_listen_port: 3200
distributor:
  receivers:
    otlp:
      protocols:
        grpc:
        http:

storage:
  trace:
    backend: local
    local:
      path: /tmp/tempo/blocks

metrics_generator:
  registry:
    external_labels:
      source: tempo  # Adds a label to all generated metrics
  storage:
    path: /var/tempo/generator/wal  # Local storage for metrics before sending
    remote_write:
      - url: "http://prometheus:9090/api/v1/write"
        send_exemplars: true  # Recommended: allows clicking a graph to see the trace

# You must also explicitly enable the processors in the overrides section
overrides:
  defaults:
    metrics_generator:
      processors: [service-graphs, span-metrics]