apiVersion: v1
kind: Service
metadata:
  name: catalog-service
  namespace: dev
spec:
  selector:
    app: catalog-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9091
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-service
  namespace: dev
  labels:
    app: catalog-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-service
  template:
    metadata:
      name: catalog-service
      labels:
        app: catalog-service
    spec:
      containers:
        - name: catalog-service
          image: catalog-service
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9091
              protocol: TCP
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-db:5432/catalog_service
            - name: BPL_JVM_THREAD_COUNT
              value: "50"
            - name: SERVER_SHUTDOWN
              value: "graceful"
            - name: SPRING_LIFECYCLE_TIMEOUT_PER_SHUTDOWN_PHASE
              value: "15s"
          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "sleep 10"]
      restartPolicy: Always
      