[INPUT]
    Name        forward
    Listen      0.0.0.0
    Port        24224

# --- New Filter to Strip Leading Slash ---
[FILTER]
    Name    lua
    Match   *
    call    remove_slash
    # Inline Lua code to remove the prefixing "/" from Docker container names
    code    function remove_slash(tag, timestamp, record) if record["container_name"] ~= nil then record["container_name"] = string.gsub(record["container_name"], "^/", "") end return 1, timestamp, record end

[Output]
    Name grafana-loki
    Match *
    Url ${LOKI_URL}
    RemoveKeys source,container_id
    Labels {job="fluent-bit"}
    LabelKeys container_name
    BatchWait 1s
    BatchSize 1001024
    LineFormat json
    LogLevel info