apiVersion: v1
kind: Service
metadata:
  name: postgres-db
spec:
  selector:
    db: postgres-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-db
  labels:
    db: postgres-db
spec:
  selector:
    matchLabels:
      db: postgres-db
  template:
    metadata:
      labels:
        db: postgres-db
    spec:
      containers:
        - name: postgres-db
          image: postgres:18.1
          env:
            - name: POSTGRES_USER
              value: catalog_service
            - name: POSTGRES_PASSWORD
              value: P@ssw0rd
            - name: POSTGRES_DB
              value: catalog_service
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
          volumeMounts:
            - mountPath: /var/lib/postgresql
              name: postgres-data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-data
      automountServiceAccountToken: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
